# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: deployenv
    type: string
    default: "NONE"
    values:
      - NONE
      - DEV
      - QA
      - UAT
      - PROD

  - name: DeploytoEnvironment
    type: boolean
    default: false

resources:
  repositories:
    - repository: kohler-azure-shared-templates
      endpoint: bitbucket-kohler
      type: bitbucket
      name: kohler_source/kohler-azure-shared-templates
      ref: refs/heads/master

     
trigger:
  branches:
    include:
      - feature/*
      - develop
      - qa
      - staging
      - master

variables:
  
  - ${{ if or( eq(parameters.deployenv, 'NONE'), contains(variables['build.sourceBranch'],'refs/heads/feature/*')) }}:
     - group: var_kohler_brazil_dev
     - name: buildcmd
       value: 'build:dev'
     - name: DeploytoApp
       value: "true" 

  - ${{ if or( eq(parameters.deployenv, 'DEV'), contains(variables['build.sourceBranch'],'refs/heads/develop')) }}:
     - group: var_kohler_brazil_dev
     - name: buildcmd
       value: 'build:dev'
     - name: DeploytoApp
       value: "true"  

  - ${{ if or(eq(parameters.deployenv, 'QA'), contains(variables['build.sourceBranch'],'refs/heads/qa')) }}:
     - group: var_kohler_brazil_qa
     - name: buildcmd
       value: 'build:qa'
     - name: DeploytoApp
       value: "true"    

  - ${{ if or(eq(parameters.deployenv, 'UAT'), contains(variables['build.sourceBranch'],'refs/heads/staging')) }}:
     - group: var_kohler_brazil_uat
     - name: buildcmd
       value: 'build:uat'
     - name: DeploytoApp
       value: "true"     

  - ${{ if or(eq(parameters.deployenv, 'PROD'), contains(variables['build.sourceBranch'],'refs/heads/master')) }}:
     - group: var_kohler_brazil_prod
     - name: buildcmd
       value: 'build:prod'
     - name: DeploytoApp
       value: "false"     

pool:
  vmImage: ubuntu-latest

stages:
- ${{ if ne( parameters['deployenv'], 'PROD') }}:
    - stage: build
      jobs:
      - job: build
        steps:    

        - template: SonarScan.yaml@kohler-azure-shared-templates
          parameters:
           SonarCloud: $(SonarCloud)
           organization: $(organization)
           ProjectKey: $(ProjectKey)
           ProjectName: $(ProjectName)
        - template: Sonaranalyze.yaml@kohler-azure-shared-templates

        - template: ArchiveFiles.yaml@kohler-azure-shared-templates
          parameters:
            rootFolderOrFile: $(Build.Repository.LocalPath)
            archiveFile: $(archiveFile)
      
        - template : PublishBuildArtifacts.yaml@kohler-azure-shared-templates
          parameters:
               PathtoPublish: '$(Build.ArtifactStagingDirectory)'
               ArtifactName: $(ArtifactName)

      - job: deploy
        dependsOn: build
        condition: and(succeeded(), or(eq( variables.deploytoApp, 'true'), ${{ eq( parameters.DeploytoEnvironment , 'true') }}))

        steps:
         - template: DownloadBuildArtifacts.yaml@kohler-azure-shared-templates
           parameters: 
             ArtifactName: $(ArtifactName)
             downloadPath: '$(System.ArtifactsDirectory)'

         - task: AzureCLI@2
           inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'az webapp deployment source config-zip  -g $(resourcegroup) -n $(appName)  --src $(System.ArtifactsDirectory)/**/kohler-brazil.zip'


- ${{ if eq( parameters['deployenv'], 'PROD') }}:
    - stage: prodbuild
      jobs:
      - job: prodbuild
        steps:    

        - template: SonarScan.yaml@kohler-azure-shared-templates
          parameters:
           SonarCloud: $(SonarCloud)
           organization: $(organization)
           ProjectKey: $(ProjectKey)
           ProjectName: $(ProjectName)
        - template: Sonaranalyze.yaml@kohler-azure-shared-templates

        - template: ArchiveFiles.yaml@kohler-azure-shared-templates
          parameters:
            rootFolderOrFile: $(Build.Repository.LocalPath)
            archiveFile: $(archiveFile)
      
        - template : PublishBuildArtifacts.yaml@kohler-azure-shared-templates
          parameters:
               PathtoPublish: '$(Build.ArtifactStagingDirectory)'
               ArtifactName: $(ArtifactName)

      - deployment: proddeployment
        dependsOn: prodbuild
        condition: and(succeeded(), or(eq( variables.deploytoApp, 'true'), ${{ eq( parameters.DeploytoEnvironment , 'true') }}))
        environment: Kohler Brazil
        strategy:
          runOnce:
            deploy:
              steps:
              - template: DownloadBuildArtifacts.yaml@kohler-azure-shared-templates
                parameters: 
                  ArtifactName: $(ArtifactName)
                  downloadPath: '$(System.ArtifactsDirectory)'

              - task: AzureCLI@2
                inputs:
                  azureSubscription: $(azureSubscription)
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: 'az webapp deployment source config-zip  -g $(resourcegroup) -n $(appName)  --src $(System.ArtifactsDirectory)/**/kohler-brazil.zip'